[project]
name = "expense"
version = "1.0.0"
description = "A basic expense log built off the Flask tutorial."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
